### ISSUE TITLE
Could not import matplotlib.pyplot

### ISSUE THREAD

**Issue by pierreloicq** [mateogianolio/matplotnode#4]
Hello,
I have the same issue as [here](https://github.com/mateogianolio/matplotnode/issues/2) but do not really understand how to resolve it.
matplotlib works when used with python.
I am on ubuntu 18.04, python 2.7 (but I have 3 too), matplotlib 2.2.4, numpy 1.16.3, matplotnode 0.3.1.
Thank you

**Comment by mateogianolio** [comment]
Thanks for submitting an issue, I will have to test on a VM with Ubuntu. I'll get back to you if I find the cause. Is the error message exactly the same as below?

```
Could not import matplotlib.pyplot.
Segmentation fault (core dumped)
```

**Comment by pierreloicq** [comment]
Thank you for your reply. Here is the exact error message:

```
Traceback (most recent call last):  
  File "/home/pierre/.local/lib/python2.7/site-packages/matplotlib/__init__.py", line 126, in <module>            
    from . import cbook 
  File "/home/pierre/.local/lib/python2.7/site-packages/matplotlib/cbook/__init__.py", line 34, in <module>                   
    import numpy as np 
  File "/home/pierre/.local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>              
    from . import core                            
  File "/home/pierre/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 71, in <module>              
    raise ImportError(msg)                                
ImportError:                                                                                                                                                                             
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!                                                            
Importing the multiarray numpy extension module failed.  Most             
likely you are trying to import a failed build of numpy.   
Here is how to proceed:       
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy. 
- If you are simply trying to use the numpy version that you have installed: 
  your installation is broken - please reinstall numpy.  
- If you have already reinstalled and that did not fix the problem, then: 1. Check that you are using the Python you expect (you're using ),
     and that you have no directories in your PATH or PYTHONPATH that can 
     interfere with the Python and numpy versions you're trying to use. 
  2. If (1) looks fine, you can open a new issue at 
     https://github.com/numpy/numpy/issues.  Please include details on:         
     - how you installed Python                 
     - how you installed numpy 
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log                
     Note: this error has many possible causes, so please don't comment on                                                    
     an existing issue about this - open a new one instead. 
Original error was: /home/pierre/.local/lib/python2.7/site-packages/numpy/core/_multiarray_umath.so: undefined symbol: PyExc_UserWarning
Could not import matplotlib.pyplot.        
Erreur de segmentation (core dumped)
```

**Comment by mateogianolio** [comment]
Hi, tested on VM with ubuntu 18.04 and I could reproduce your error. After some digging I managed to fix it, so I just published 0.3.2. I have tested it and it seems to work now. Please tell me if you still have problems and I will reopen this issue.

**Comment by pierreloicq** [comment]
Hi, unfortunately it still crashes. Now 

> Erreur de segmentation (core dumped)

is the only message.

>  npm list matplotnode
> └── matplotnode@0.3.2
